services:
  auth-app:
    build:
      context: .
      dockerfile: apps/auth-app/Dockerfile
    container_name: auth-app
    ports:
      - "3005:3005"
    env_file:
      - apps/auth-app/.env
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "3010:3010"
    env_file:
      - apps/auth-service/.env
    environment:
      - NODE_ENV=development
      - PORT=3010
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
