services:
  auth-app:
    build:
      context: .
      dockerfile: apps/auth-app/Dockerfile
    container_name: auth-app
    ports:
      - "3005:3005"
    env_file:
      - apps/auth-app/.env
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "3010:3010"
    env_file:
      - apps/auth-service/.env
    restart: unless-stopped
