services:
  auth-app:
    build:
      context: .
      dockerfile: ./apps/auth-app/Dockerfile
    container_name: auth-app
    ports:
      - "3005:3005"
    volumes:
      - -:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
