import { Brand } from "../types/brands";
import { Product } from "../types/products";

export const brandsTest: Brand[] = [
  {
    id: "1",
    name: "ASUS",
    logo: "",
    website: "",
    isActive: false,
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "2",
    name: "Gigabyte",
    logo: "",
    website: "",
    isActive: false,
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "3",
    name: "Intel",
    logo: "",
    website: "",
    isActive: false,
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "4",
    name: "ColorFul",
    logo: "",
    website: "",
    isActive: false,
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "5",
    name: "AsRock",
    logo: "",
    website: "",
    isActive: false,
    createAt: new Date(),
    updateAt: new Date(),
  },
];

export const productTest: Product[] = [
  {
    id: "",
    name: "Mother A1",
    description: "",
    comparePrice: 0,
    price: 0,
    stock: 0,
    minStock: 0,
    categoryId: "",
    brandId: "",
    imageUrl: "",
    images: [""],
    tags: [""],
    specification: {},
    discountPercentage: 0,
    discountStartDate: new Date(),
    discountEndDate: new Date(),
    isActive: false,
    isFeatured: false,
    weight: 0,
    dimension: 0,
    slug: "",
    views: 0,

    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "",
    name: "Mother A2",
    description: "",
    comparePrice: 0,
    price: 0,
    stock: 0,
    minStock: 0,
    categoryId: "",
    brandId: "",
    imageUrl: "",
    images: [""],
    tags: [""],
    specification: {},
    discountPercentage: 0,
    discountStartDate: new Date(),
    discountEndDate: new Date(),
    isActive: false,
    isFeatured: false,
    weight: 0,
    dimension: 0,
    slug: "",
    views: 0,

    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "",
    name: "Procesador A1",
    description: "",
    comparePrice: 0,
    price: 0,
    stock: 0,
    minStock: 0,
    categoryId: "",
    brandId: "",
    imageUrl: "",
    images: [""],
    tags: [""],
    specification: {},
    discountPercentage: 0,
    discountStartDate: new Date(),
    discountEndDate: new Date(),
    isActive: false,
    isFeatured: false,
    weight: 0,
    dimension: 0,
    slug: "",
    views: 0,

    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "",
    name: "Procesador A2",
    description: "",
    comparePrice: 0,
    price: 0,
    stock: 0,
    minStock: 0,
    categoryId: "",
    brandId: "",
    imageUrl: "",
    images: [""],
    tags: [""],
    specification: {},
    discountPercentage: 0,
    discountStartDate: new Date(),
    discountEndDate: new Date(),
    isActive: false,
    isFeatured: false,
    weight: 0,
    dimension: 0,
    slug: "",
    views: 0,

    createdAt: new Date(),
    updateAt: new Date(),
  },
];
